version: '3.12'
services:
  anki:  # 服务名称
    container_name: anki  # 容器名称
    image: anki/syncd:v25.02.4 
    restart: always

    env_file:
      - ./envs/pub.env
      - ./envs/users.env

    network_mode: bridge
    ports:
      - "8080:8080/tcp"

    sysctls:
      - net.ipv4.tcp_ecn=1
      - net.ipv4.tcp_ecn_fallback=1
      - net.ipv4.tcp_dsack=1
      - net.ipv4.tcp_fack=1
      - net.ipv4.tcp_sack=1
      - net.ipv4.conf.all.rp_filter=1
      - net.ipv4.conf.default.rp_filter=1
      # - net.ipv4.ip_forward=1
      - net.ipv4.tcp_keepalive_intvl=15
      - net.ipv4.tcp_keepalive_probes=5
      - net.ipv4.tcp_keepalive_time=75
      - net.ipv4.tcp_fastopen=3
      - net.ipv4.tcp_moderate_rcvbuf=1
      - net.ipv4.tcp_mtu_probing=2
      - net.ipv4.tcp_syncookies=1
      - net.ipv4.tcp_timestamps=1
      - net.ipv4.tcp_window_scaling=1

    volumes:
      - "./data.d/:/opt/anki.d/"
      - "/etc/localtime:/etc/localtime:ro"
