name: Build the Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to container
        env:
          REGISTRY_URL: https://git.httpx.online:443
        run: |
          echo ${{ secrets.GITEA_TOKEN }} | docker login -u ${{ secrets.GITEA_USER }} https://git.httpx.online:443 --password-stdin

      - name: Get Version
        id: get_version
        run: |
          if [ ! -f .github/version ]; then
            echo "Error: Version file not found!"
            exit 1
          fi
          version=$(cat .github/version)
          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "Anki Releases Version: ${version}"

      - name: Build the Docker image
        run: |
          docker buildx build \
            . \
            --file Dockerfile \
            --build-arg ANKI_VERSION=${{ env.VERSION }} \
            --tag anki_syncd:v${{ env.VERSION }}

      - name: Save Docker image
        run: |
          docker save \
            -o anki_syncd_${{ env.VERSION }}.tar \
            anki_syncd:v${{ env.VERSION }}

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: anki_syncd:v${{ env.VERSION }}.tar
          path: anki_syncd_${{ env.VERSION }}.tar

      - name: Push Docker image
        env:
          DOCKER_IMAGE: anki_syncd:v${{ env.VERSION }}
          GITEA_REPO: ${{ secrets.GITEA_SERVICE }}/${{ secrets.GITEA_USER }}/anki_syncd:v${{ env.VERSION }}
        run: |
          docker tag $DOCKER_IMAGE $GITEA_REPO
          docker push $GITEA_REPO
          